// <auto-generated />
using System;
using App.Models.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace App.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("App.Models.Marque", b =>
                {
                    b.Property<int>("IdMarque")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_marque");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMarque"));

                    b.Property<string>("NomMarque")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nom_marque");

                    b.HasKey("IdMarque");

                    b.ToTable("Marque");
                });

            modelBuilder.Entity("App.Models.Produit", b =>
                {
                    b.Property<int>("IdProduit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_produit");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdProduit"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("IdMarque")
                        .HasColumnType("integer")
                        .HasColumnName("id_marque");

                    b.Property<int?>("IdTypeProduit")
                        .HasColumnType("integer")
                        .HasColumnName("id_type_produit");

                    b.Property<string>("NomPhoto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nom_photo");

                    b.Property<string>("NomProduit")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nom_produit");

                    b.Property<int>("StockMax")
                        .HasColumnType("integer")
                        .HasColumnName("stock_max");

                    b.Property<int>("StockMin")
                        .HasColumnType("integer")
                        .HasColumnName("stock_min");

                    b.Property<int>("StockReel")
                        .HasColumnType("integer")
                        .HasColumnName("stock_reel");

                    b.Property<string>("UriPhoto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("uri_photo");

                    b.HasKey("IdProduit");

                    b.HasIndex("IdMarque");

                    b.HasIndex("IdTypeProduit");

                    b.ToTable("produit");
                });

            modelBuilder.Entity("App.Models.TypeProduit", b =>
                {
                    b.Property<int>("IdTypeProduit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_type_produit");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTypeProduit"));

                    b.Property<string>("NomTypeProduit")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nom_type_produit");

                    b.HasKey("IdTypeProduit");

                    b.ToTable("TypeProduit");
                });

            modelBuilder.Entity("App.Models.Produit", b =>
                {
                    b.HasOne("App.Models.Marque", "MarqueNavigation")
                        .WithMany("Produits")
                        .HasForeignKey("IdMarque")
                        .HasConstraintName("FK_produits_marque");

                    b.HasOne("App.Models.TypeProduit", "TypeProduitNavigation")
                        .WithMany("Produits")
                        .HasForeignKey("IdTypeProduit")
                        .HasConstraintName("FK_produits_type_produit");

                    b.Navigation("MarqueNavigation");

                    b.Navigation("TypeProduitNavigation");
                });

            modelBuilder.Entity("App.Models.Marque", b =>
                {
                    b.Navigation("Produits");
                });

            modelBuilder.Entity("App.Models.TypeProduit", b =>
                {
                    b.Navigation("Produits");
                });
#pragma warning restore 612, 618
        }
    }
}
